# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='values',
            new_name='value',
        ),
    ]
