# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20161031_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='picture',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
